server:
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: luo990610
    username: root
    url: dbc:mysql://localhost:3306/networksecurity?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  config-location:
  type-aliases-package:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
